### ISSUE TITLE
Suggest/require a new version of Visual Studio C++

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/Vid-Extension#35] opened 2022-06-23 19:55 UTC
Currently if the library is missing we ask the user to install Visual Studio 2010 (VC++ 10.0) SP1 which is no longer supported.
We should use a more recent version found at https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 unless that causes problems.

_extensions/vid/src/main/scala/PlatformErrors.scala_

```
  def showMissingVcppRuntimeMessage(ex: java.lang.ExceptionInInitializerError) = {
    val is64 = System.getProperty("os.arch").contains("64")
    // URLs are taken from here: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2010-vc-100-sp1-no-longer-supported
    val url = if (is64) {
      "https://aka.ms/highdpimfc2013x64enu"
    } else {
      "https://aka.ms/highdpimfc2013x86enu"
    }
    val message = s"It appears that a Windows library needed by the Vid extension is not installed.  Please visit this link to download the Microsoft Visual C++ 10 runtime library installer: $url\n\nAfter installing it try running the Vid extension one more time."
    showDialog("Missing Windows Library", message, ex)
  }
```

Note this issue might become moot if we address
[Using redundant camera libraries #32](https://github.com/NetLogo/Vid-Extension/issues/32)

**Comment by LaCuneta** [comment] 2022-07-05 14:10
We don't control the VC++ lib version used, that comes from the capture libraries.  We'd need to update the libraries we're using and get the change merged or fork them and make our own, which is what #32 suggests.  So I'm closing this as a duplicate of that one.

**Closed by LaCuneta** 2022-07-05 14:10 UTC
